# Generated by Django 4.1 on 2022-09-10 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
