# Generated by Django 4.0.7 on 2022-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
