# Generated by Django 4.0.7 on 2022-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_brand_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
