# Generated by Django 4.1 on 2022-09-14 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
