# Generated by Django 4.0.7 on 2022-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_product_name_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
