# Generated by Django 4.0.7 on 2022-09-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
