# Generated by Django 4.0.7 on 2022-09-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
