# Generated by Django 4.0.7 on 2022-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_variation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
