# Generated by Django 4.0.7 on 2022-09-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
    ]
