# Generated by Django 4.1.1 on 2022-10-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_products_is_discount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
    ]
