# Generated by Django 4.1.1 on 2022-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_products_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_discount_active',
            new_name='offer_statuspro',
        ),
        migrations.AddField(
            model_name='products',
            name='offer_product',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
