# Generated by Django 4.1.1 on 2022-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
