# Generated by Django 4.1.1 on 2022-10-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_rename_is_discount_activate_category_is_discount_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discount',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_discount_active',
            new_name='offer_status',
        ),
    ]
