# Generated by Django 4.1.1 on 2022-10-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_rename_discount_category_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='offer_status',
            new_name='offerstatus',
        ),
    ]
