# Generated by Django 4.1.1 on 2022-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
