# Generated by Django 4.1.1 on 2022-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_discount_reduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
