# Generated by Django 4.1.1 on 2022-10-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_alter_discount_total_discount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="discount",
        ),
    ]
