# Generated by Django 4.1.1 on 2022-10-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_orderproduct_return_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="ordered",
            new_name="orderproduct_cancel",
        ),
    ]
